DROP TABLE IF EXISTS Game;

DROP TABLE IF EXISTS Tournament;

DROP TABLE IF EXISTS Place;

DROP TABLE IF EXISTS Employee_Data;


DROP TABLE IF EXISTS Staff;

DROP TABLE IF EXISTS Player;

DROP TABLE IF EXISTS Coach;
